
DEFAULT_OBJECTS_TYPE_KEY = "__type__"
DEFAULT_OBJECTS_ATTRS_KEY = "__attrs__"
DEFAULT_OBJECTS_ITEMS_KEY = "__items__"

DEFAULT_OBJECTS_PARENT_ATTR = "_parent"
DEFAULT_OBJECTS_PARENT_ATTR_ENABLED = True
